FeaturesToDrop = [
    "lob",
    "split",
    "account_number",
]


CategoricalFeaturesToGroup = [
    'industry',
    'state',
]

CategoricalFeaturesToTargetEncode = [
    'industry',
    'state',
]

CategoricalFeaturesToOneHot = [
    'industry_grouped',
    'litigation_grouped',
    'weather_grouped',
    'exposure_base'
]

IndustryGrouping = {
    'Agriculture': '1',
    'Auto Dealers & Repairs': '1',
    'Transportation': '1',
    'Trucking': '1',
    'Finance': '1',
    'Government': '1',
    'Healthcare': '1',
    'Life Sciences': '1',
    'Communication': '2',
    'Manufacturing': '2',
    'Mining': '2',
    'Energy': '2',
    'Membership Organizations': '3',
    'Education': '3',
    'Services': '3',
    'Technology': '3',
    'Utilities': '3',
    'Wholesale': '3',
    'Construction': '4',
    'Entertainment': '5',
    'Hospitality': '5',
    'Misc Repair': '5',
    'Real Estate': '5',
    'Restaurants': '5',
    'Retail': '5'
}


LitigationGrouping = {
    'CA': 'High',
    'NY': 'High',
    'FL': 'High',
    'IL': 'High',
    'TX': 'High',
    'PA': 'High',
    'NJ': 'Moderate-High',
    'MA': 'Moderate-High',
    'GA': 'Moderate-High',
    'LA': 'Moderate-High',
    'OH': 'Moderate',
    'MI': 'Moderate',
    'CO': 'Moderate',
    'AZ': 'Moderate',
    'MN': 'Moderate',
    'NC': 'Low-Moderate',
    'VA': 'Low-Moderate',
    'IN': 'Low-Moderate',
    'TN': 'Low-Moderate',
    'CT': 'Low-Moderate',
    'HI': 'Low-Moderate',
    'IA': 'Low-Moderate',
    'KS': 'Low-Moderate',
    'KY': 'Low-Moderate',
    'ME': 'Low-Moderate',
    'MD': 'Low-Moderate',
    'MO': 'Low-Moderate',
    'MS': 'Low-Moderate',
    'NE': 'Low-Moderate',
    'NV': 'Low-Moderate',
    'NH': 'Low-Moderate',
    'NM': 'Low-Moderate',
    'OK': 'Low-Moderate',
    'OR': 'Low-Moderate',
    'RI': 'Low-Moderate',
    'SC': 'Low-Moderate',
    'SD': 'Low-Moderate',
    'UT': 'Low-Moderate',
    'VT': 'Low-Moderate',
    'WA': 'Low-Moderate',
    'WI': 'Low-Moderate',
    'WV': 'Low-Moderate',
    'WY': 'Low',
    'ID': 'Low',
    'MT': 'Low',
    'ND': 'Low',
    'DE': 'Low',
    'AL': 'Low',
    'AK': 'Low',
    'AR': 'Low',
    'DC': 'Low',
    'PR': 'Low'
}


WeatherExposureGrouping = {
    'AL': 'Moderate-High',
    'AK': 'Low',
    'AZ': 'Low-Moderate',
    'AR': 'Moderate-High',
    'CA': 'Low',
    'CO': 'Low-Moderate',
    'CT': 'Moderate',
    'DE': 'Low-Moderate',
    'FL': 'High',
    'GA': 'Moderate-High',
    'HI': 'Low',
    'ID': 'Low',
    'IL': 'Moderate',
    'IN': 'Low-Moderate',
    'IA': 'Moderate-High',
    'KS': 'Moderate-High',
    'KY': 'Moderate',
    'LA': 'High',
    'ME': 'Low-Moderate',
    'MD': 'Low-Moderate',
    'MA': 'Moderate',
    'MI': 'Moderate',
    'MN': 'Moderate',
    'MS': 'Moderate-High',
    'MO': 'Moderate-High',
    'MT': 'Low-Moderate',
    'NE': 'Moderate-High',
    'NV': 'Moderate',
    'NH': 'Low-Moderate',
    'NJ': 'Moderate',
    'NM': 'Low-Moderate',
    'NY': 'Moderate-High',
    'NC': 'High',
    'ND': 'Low',
    'OH': 'Low-Moderate',
    'OK': 'Moderate-High',
    'OR': 'Low',
    'PA': 'Low-Moderate',
    'RI': 'Moderate',
    'SC': 'Moderate-High',
    'SD': 'Low',
    'TN': 'Moderate',
    'TX': 'High',
    'UT': 'Low-Moderate',
    'VT': 'Low',
    'VA': 'Moderate-High',
    'WA': 'Low',
    'WV': 'Low-Moderate',
    'WI': 'Moderate',
    'WY': 'Low-Moderate',
    'PR': 'Moderate-High',
    'DC': 'Moderate'
}


GDP = {
    'AK' : 'Low',
    'AL' : 'Moderate',
    'AR' : 'Low-Moderate',
    'AZ' : 'Moderate-High',
    'CA' : 'High',
    'CO' : 'Moderate-High',
    'CT' : 'Moderate',
    'DC' : 'Low-Moderate',
    'DE' : 'Low',
    'FL' : 'High',
    'GA' : 'High',
    'HI' : 'Low-Moderate',
    'IA' : 'Moderate',
    'ID' : 'Low-Moderate',
    'IL' : 'High',
    'IN' : 'Moderate-High',
    'KS' : 'Low-Moderate',
    'KY' : 'Moderate',
    'LA' : 'Moderate',
    'MA' : 'Moderate-High',
    'MD' : 'Moderate-High',
    'ME' : 'Low',
    'MI' : 'Moderate-High',
    'MN' : 'Moderate-High',
    'MO' : 'Moderate',
    'MS' : 'Low-Moderate',
    'MT' : 'Low',
    'NC' : 'High',
    'ND' : 'Low',
    'NE' : 'Low-Moderate',
    'NH' : 'Low-Moderate',
    'NJ' : 'High',
    'NM' : 'Low-Moderate',
    'NV' : 'Low-Moderate',
    'NY' : 'High',
    'OH' : 'High',
    'OK' : 'Moderate',
    'OR' : 'Moderate',
    'PA' : 'High',
    'PR' : 'Low',
    'RI' : 'Low',
    'SC' : 'Moderate',
    'SD' : 'Low',
    'TN' : 'Moderate-High',
    'TX' : 'High',
    'UT' : 'Moderate',
    'VA' : 'Moderate-High',
    'VT' : 'Low',
    'WA' : 'High',
    'WI' : 'Moderate-High',
    'WV' : 'Low',
    'WY' : 'Low'
}

LivingCost = {
    'AK' : 'High',
    'AL' : 'Low',
    'AR' : 'Low',
    'AZ' : 'Moderate-High',
    'CA' : 'High',
    'CO' : 'Moderate-High',
    'CT' : 'Moderate-High',
    'DC' : 'High',
    'DE' : 'Moderate',
    'FL' : 'Moderate',
    'GA' : 'Low-Moderate',
    'HI' : 'High',
    'IA' : 'Low',
    'ID' : 'Moderate-High',
    'IL' : 'Low',
    'IN' : 'Low-Moderate',
    'KS' : 'Low',
    'KY' : 'Low-Moderate',
    'LA' : 'Low-Moderate',
    'MA' : 'High',
    'MD' : 'High',
    'ME' : 'Moderate-High',
    'MI' : 'Low-Moderate',
    'MN' : 'Low-Moderate',
    'MO' : 'Low',
    'MS' : 'Low',
    'MT' : 'Moderate-High',
    'NC' : 'Moderate',
    'ND' : 'Moderate',
    'NE' : 'Low',
    'NH' : 'High',
    'NJ' : 'Moderate-High',
    'NM' : 'Moderate',
    'NV' : 'Moderate',
    'NY' : 'High',
    'OH' : 'Low-Moderate',
    'OK' : 'Low',
    'OR' : 'High',
    'PA' : 'Moderate',
    'PR' : 'Moderate-High',
    'RI' : 'Moderate-High',
    'SC' : 'Moderate',
    'SD' : 'Low-Moderate',
    'TN' : 'Low',
    'TX' : 'Low-Moderate',
    'UT' : 'Moderate',
    'VA' : 'Moderate-High',
    'VT' : 'High',
    'WA' : 'High',
    'WI' : 'Moderate',
    'WV' : 'Low',
    'WY' : 'Low-Moderate'
}


CorporateTax = {
    'AK' : 'High',
    'AL' : 'Moderate',
    'AR' : 'Low-Moderate',
    'AZ' : 'Low-Moderate',
    'CA' : 'High',
    'CO' : 'Low',
    'CT' : 'Moderate-High',
    'DC' : 'Moderate',
    'DE' : 'High',
    'FL' : 'Low-Moderate',
    'GA' : 'Low-Moderate',
    'HI' : 'Moderate',
    'IA' : 'High',
    'ID' : 'Low-Moderate',
    'IL' : 'High',
    'IN' : 'Low-Moderate',
    'KS' : 'Moderate-High',
    'KY' : 'Low-Moderate',
    'LA' : 'Moderate-High',
    'MA' : 'Moderate-High',
    'MD' : 'High',
    'ME' : 'High',
    'MI' : 'Moderate',
    'MN' : 'High',
    'MO' : 'Low',
    'MS' : 'Low-Moderate',
    'MT' : 'Moderate',
    'NC' : 'Low',
    'ND' : 'Low',
    'NE' : 'Moderate-High',
    'NH' : 'Moderate-High',
    'NJ' : 'High',
    'NM' : 'Moderate',
    'NV' : 'Low',
    'NY' : 'Moderate-High',
    'OH' : 'Low',
    'OK' : 'Low',
    'OR' : 'Moderate-High',
    'PA' : 'High',
    'PR' : 'Moderate',
    'RI' : 'Moderate-High',
    'SC' : 'Low-Moderate',
    'SD' : 'Low',
    'TN' : 'Moderate',
    'TX' : 'Low',
    'UT' : 'Low-Moderate',
    'VA' : 'Moderate',
    'VT' : 'High',
    'WA' : 'Low',
    'WI' : 'Moderate-High',
    'WV' : 'Moderate',
    'WY' : 'Low'
}

AvgLaborCost = {
    'AK' : 'High',
    'AL' : 'Low',
    'AR' : 'Low',
    'AZ' : 'Moderate-High',
    'CA' : 'High',
    'CO' : 'High',
    'CT' : 'High',
    'DC' : 'Moderate-High',
    'DE' : 'Moderate-High',
    'FL' : 'Moderate',
    'GA' : 'Moderate',
    'HI' : 'Moderate-High',
    'IA' : 'Low-Moderate',
    'ID' : 'Low',
    'IL' : 'Moderate-High',
    'IN' : 'Low-Moderate',
    'KS' : 'Low-Moderate',
    'KY' : 'Low',
    'LA' : 'Low',
    'MA' : 'High',
    'MD' : 'High',
    'ME' : 'Moderate',
    'MI' : 'Moderate',
    'MN' : 'Moderate-High',
    'MO' : 'Low-Moderate',
    'MS' : 'Low',
    'MT' : 'Low',
    'NC' : 'Moderate',
    'ND' : 'Low-Moderate',
    'NE' : 'Low-Moderate',
    'NH' : 'Moderate-High',
    'NJ' : 'High',
    'NM' : 'Low-Moderate',
    'NV' : 'Low-Moderate',
    'NY' : 'High',
    'OH' : 'Moderate',
    'OK' : 'Low',
    'OR' : 'Moderate-High',
    'PA' : 'Moderate',
    'PR' : 'Moderate-High',
    'RI' : 'High',
    'SC' : 'Low',
    'SD' : 'Low',
    'TN' : 'Low-Moderate',
    'TX' : 'Moderate',
    'UT' : 'Moderate',
    'VA' : 'High',
    'VT' : 'Moderate-High',
    'WA' : 'High',
    'WI' : 'Moderate',
    'WV' : 'Low',
    'WY' : 'Low-Moderate'
}

